WebApplication/mysite/PointsOfInterest/urls.py
from django.conf.urls import patterns, url

from PointsOfInterest import views

urlpatterns = patterns('PointsOfInterest',
	url(r'^$', views.index, name='index'),
	#url(r'^place/(?P<placeid>\d+)/$', views.place, name='place'),
	url(r'^place/(?P<placeid>\d+)/$', views.place, name='place'),
	url(r'^(?P<userid>\d+)/places/$', views.places, name='places'),
	url(r'^places/$', views.places, name='places'),
	url(r'^friends/$', views.friends, name='friends' ),
	url(r'^settings/$', views.settings, name='settings' ),
	url(r'^createpoi/$', views.createpoi, name='createpoi' ),
	url(r'^login/$', views.logging, name='login' ),
	url(r'^logout/$', views.loggingout, name='logout' ),
)

WebApplication/mysite/mysite/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^POI/', include('PointsOfInterest.urls', namespace='PointsOfInterest')),
)

WebApplication/mysite/PointsOfInterest/models.py
from django.db import models
from django import forms

class User(models.Model):
<<<<<<< HEAD
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=50)
    nickname = models.CharField(max_length=20)
    email = models.CharField(max_length=50)
    password = models.CharField(max_length=30)
    friends = models.ForeignKey('self', blank=True, default='null',on_delete=models.SET_DEFAULT);

=======
	first_name = models.CharField(max_length=30)
	last_name = models.CharField(max_length=50)
	nickname = models.CharField(max_length=20)
	email = models.CharField(max_length=50)
	password = models.CharField(max_length=30)

class Friend(models.Model):
	friends = models.ForeignKey(User)
>>>>>>> 327913c346d6ee17b434c878952817f8e2b41515

class CategoryOfPoi(models.Model):
	category_name = models.CharField(max_length=30)

class Photo(models.Model):
	title = models.CharField(max_length=30)

class PointOfInterest(models.Model):
	user = models.ForeignKey(User)
	latitude = models.FloatField(max_length=30)
	longitude = models.FloatField(max_length=30)
	title = models.CharField(max_length=30)
	description = models.CharField(max_length=200)
	category = models.ForeignKey(CategoryOfPoi)
	photos = models.ForeignKey(Photo)


class CreatePoi(forms.Form):
	title = forms.CharField(required=True, max_length=100, initial="")
	description = forms.CharField(required=True, widget=forms.Textarea, initial="")
	latitude = forms.CharField(widget=forms.HiddenInput)
	longitude = forms.CharField(widget=forms.HiddenInput)

class Login(forms.Form):
	username = forms.CharField(required=True, max_length=30, initial="")
	password = forms.CharField(max_length=32, widget=forms.PasswordInput, initial="")
	#widget=forms.HiddenInput



# Create your models here.

WebApplication/mysite/PointsOfInterest/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.template import RequestContext, loader
<<<<<<< HEAD
from django.shortcuts import render

def index(request):
    template = loader.get_template('sablona/index.html')
    
    context = RequestContext(request)
    return HttpResponse(template.render(context))
=======
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.contrib import auth


from django.contrib.auth.models import User


from PointsOfInterest.models import PointOfInterest
from PointsOfInterest.models import CreatePoi
from PointsOfInterest.models import Login


def index(request):
	return HttpResponse("Hello, world. You're at our exciting site about Points of Interest")

def loggingout(request):
	auth.logout(request)
	template = loader.get_template('PointsOfInterest/login.html')
	context = RequestContext(request, {	})
	return HttpResponse(template.render(context))


def logging(request):
	#request.session['test'] = 'test'
	if request.method == 'POST':
		username = request.POST['username']
		password = request.POST['password']
		user = authenticate(username=username, password=password)
		if user is not None:
			if user.is_active:
				login(request, user)
				request.session['logged'] = user.id
				# Redirect to a success page.
				template = loader.get_template('PointsOfInterest/login.html')
				context = RequestContext(request, { 'logged' : True })
				return HttpResponse(template.render(context))
			else:
				# Return a 'disabled account' error message
				return HttpResponse("Ucet neaktivny")
		else:
			# Return an 'invalid login' error message.
			# return HttpResponse("Neprihlaseny")
			template = loader.get_template('PointsOfInterest/login.html')
			context = RequestContext(request, { 'message' :"Nespravne prihlasovacie udaje", 'logged' : False,	})
			return HttpResponse(template.render(context))
	elif 'logged' in request.session:
		template = loader.get_template('PointsOfInterest/login.html')
		context = RequestContext(request, { 'message' :"Uz ste prihlaseny", 'logged' : True,	})
		return HttpResponse(template.render(context))
	else:
		template = loader.get_template('PointsOfInterest/login.html')
		context = RequestContext(request, { 'logged' : False, })
		return HttpResponse(template.render(context))



def place(request, placeid):
	place = PointOfInterest.objects.get(id=placeid)
	template = loader.get_template('PointsOfInterest/place.html')
	context = RequestContext(request, {
		'place': place,
		})
	return HttpResponse(template.render(context))

@login_required(login_url='/POI/login/')
def places(request):
	userid = request.session['logged']
	places = PointOfInterest.objects.filter(user_id=userid)
	template = loader.get_template('PointsOfInterest/places.html')
	context = RequestContext(request, {
        'places': places,
        })
	return HttpResponse(template.render(context))



def createpoi(request):
	if request.method == 'POST': # If the form has been submitted...
		form = CreatePoi(request.POST) # A form bound to the POST data
		if form.is_valid(): # All validation rules pass
			# Process the data in form.cleaned_data
			# ...

			place = PointOfInterest()
			place.title = form.cleaned_data['title']
			place.description = form.cleaned_data['description']
			place.latitude = form.cleaned_data['latitude']
			place.longitude = form.cleaned_data['longitude']
			place.user_id = 1
			place.category_id = 1
			place.photos_id = 1

			place.save()

			template = loader.get_template('PointsOfInterest/index.html')
			context = RequestContext(request, {
		})
		return HttpResponse(template.render(context))
			#return HttpResponse('/POI/index.html')
	else:
		form = CreatePoi() # An unbound form
		template = loader.get_template('PointsOfInterest/createpoi.html')
		"""return render(request, 'PointsOfInterest/createpoi.html', {
			'form': form
		})"""
		context = RequestContext(request, {
			'form': form,
		})
		return HttpResponse(template.render(context))



def friends(request):
	return HttpResponse("Stranka priatelia")

def settings(request):
	return HttpResponse("Stranka nastavenia")



>>>>>>> 327913c346d6ee17b434c878952817f8e2b41515

    #place = PointOfInterest.objects.get(id=placeid)
	#template = loader.get_template('PointsOfInterest/places.html')
    #context = RequestContext(request, { } )
    #    'place': place,
    #    })
    #return HttpResponse(template.render(context))
    #return HttpResponse("You're looking at the results of poll %s." % p.title)
	#return HttpResponse(template.render(1))

WebApplication/mysite/PointsOfInterest/templates/PointsofInterest/createpoi.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>

<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<title>Vytvoriť bod</title>
<link href="/static/style.css" rel="stylesheet" type="text/css">



<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCC5vyrqbcCQRVny8dQP5KhGq3W96kkfcU&sensor=false"></script>

	<script type="text/javascript">

		var map;
		var marker;
		
		
		function initialize() {
			var myLatlng = new google.maps.LatLng(-25.363882,131.044922);
			var mapOptions = {
				zoom: 10,
				center: myLatlng
			};
			map = new google.maps.Map(document.getElementById("map-canvas"), mapOptions);
			
			google.maps.event.addListener(map, 'click', function(event) {
				placeMarker(event.latLng); });
			}

		function placeMarker(location) {
			if (marker) {
				marker.setPosition(location);
			}
			else {
				marker = new google.maps.Marker({
					position: location,
					map: map,
					draggable: false,
					title: "Nový bod"
				});
			}
			map.setCenter(location);

			var formlat = document.getElementById("id_latitude");
			var formlng = document.getElementById("id_longitude");
			formlat.value = marker.getPosition().lat();
			formlng.value = marker.getPosition().lng();
		}

		google.maps.event.addDomListener(window, 'load', initialize);

	</script>
	
</head>

<body>

<div class="container">

  <div class="header"></div>
  
	<div class="menu_div">
		<table class="menu_table">
			<tr class="menu makeborder">
				<td><a href="{% url 'PointsOfInterest:index' %}">Domov</a></td>
				<td><a href="{% url 'PointsOfInterest:friends' %}">Priatelia</a></td>
				<td><a href="{% url 'PointsOfInterest:places' 1 %}">Moje miesta</a></td>
				<td><a href="{% url 'PointsOfInterest:settings' %}">Nastavenie</a></td>
			</tr>
		</table>
	</div>
			
	<div class="content makeborder makeshadow">
		<div id="map-canvas" class="createpoi_map fltrt"></div>
		<div width="auto">
			<div align="center"><h2>Vytvoriť nový bod</h2></div>
			<div style="padding:0px 20px;">
				<form action="{% url 'PointsOfInterest:createpoi' %}" method="post">{% csrf_token %}

					{{ form.non_field_errors }}
					<div class="fieldWrapper">
						{{ form.title.errors }}
						<label for="id_title">Názov bodu:</label><br>
						{{ form.title }}
					</div>
					<div class="fieldWrapper">
						{{ form.description.errors }}
						<label for="id_description">Popis bodu:</label>
					</div>
					<div>
						{{ form.description }}
					</div>
					<div id="map_latitude" class="fieldWrapper">
						{{ form.latitude }}
					</div>
					<div id="map_longitude" class="fieldWrapper">
						{{ form.longitude }}
					</div>
					<p><input type="submit" value="Vytvoriť tento bod" /></p>
				</form>
			</div>
		<div class="clearfloat"></div>
		</div>
	</div>

	<div class="footer"></div>
</div>

</body>
</html>

WebApplication/mysite/PointsOfInterest/templates/PointsofInterest/friends.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<title>Dokument bez názvu</title>
<link href="style.css" rel="stylesheet" type="text/css">

<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCC5vyrqbcCQRVny8dQP5KhGq3W96kkfcU&sensor=false"></script>
	<script type="text/javascript">
		function initialize()
		{
        var mapOptions = {
          center: new google.maps.LatLng(48.717, 21.25),
          zoom: 8,
          mapTypeId: google.maps.MapTypeId.ROADMAP
        };
        var map = new google.maps.Map(document.getElementById("map-canvas-01"), mapOptions);
		
		var MarkerOptions = {
			position: new google.maps.LatLng(48.717, 21.25),
			map: map,
			title: 'Moje oblubene miesto'
		};
		var marker = new google.maps.Marker(MarkerOptions);
		
		
		
		var mapOptions = {
		  center: new google.maps.LatLng(31.717, 31.25),
          zoom: 8,
          mapTypeId: google.maps.MapTypeId.ROADMAP
        };
		
		var map = new google.maps.Map(document.getElementById("map-canvas-02"), mapOptions);
		
		var MarkerOptions = {
			position: new google.maps.LatLng(31.717, 31.25),
			map: map,
			title: 'Tu som bol pri mori'
		};
		var marker = new google.maps.Marker(MarkerOptions);
			
		
		}
      google.maps.event.addDomListener(window, 'load', initialize);
    </script>
  </head>



</head>

<body>

<div class="container">

  <div class="header">
  </div>
  	<div class="menu_div">
    		<table class="menu_table"><tr class="menu"><td><a href="index.html">Domov</a></td><td><a href="friends.html">Priatelia</a></td><td><a href="places.html">Moje miesta</a></td><td><a href="null">Nastavenie</a></td></tr></table>
   	</div>
  <div class="content">
  
  	<div class="friend">
    <img class="friend_photo" src="http://upload.wikimedia.org/wikipedia/commons/thumb/0/0c/Mark_Dayton_official_photo.jpg/819px-Mark_Dayton_official_photo.jpg">
    <div align="center">Jozef123</div>
    </div>
    
    
    <div class="friend">
    <img class="friend_photo" src="http://domaingang.com/wp-content/uploads/2010/11/enom-girl.jpg">
    <div align="center">Janka555</div>
    </div>
    <div class="clearfloat"></div>  
    
    
  	
    <!-- end .content --></div>
    <div class="footer"></div>
  <!-- end .container --></div>
</body>
</html>

WebApplication/mysite/PointsOfInterest/templates/PointsofInterest/index.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<title>Dokument bez názvu</title>
<link href="style.css" rel="stylesheet" type="text/css">

<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCC5vyrqbcCQRVny8dQP5KhGq3W96kkfcU&sensor=false"></script>
	<script type="text/javascript">
		function initialize()
		{
        var mapOptions = {
          center: new google.maps.LatLng(48.717, 21.25),
          zoom: 8,
          mapTypeId: google.maps.MapTypeId.ROADMAP
        };
        var map = new google.maps.Map(document.getElementById("map-canvas-01"), mapOptions);
		
		var MarkerOptions = {
			position: new google.maps.LatLng(48.717, 21.25),
			map: map,
			title: 'Krasne miesto'
		};
		var marker = new google.maps.Marker(MarkerOptions);
		
		
		
		var mapOptions = {
		  center: new google.maps.LatLng(31.717, 31.25),
          zoom: 8,
          mapTypeId: google.maps.MapTypeId.ROADMAP
        };
		
		var map = new google.maps.Map(document.getElementById("map-canvas-02"), mapOptions);
		
		var MarkerOptions = {
			position: new google.maps.LatLng(31.717, 31.25),
			map: map,
			title: 'Moja mladost'
		};
		var marker = new google.maps.Marker(MarkerOptions);
			
		
		}
      google.maps.event.addDomListener(window, 'load', initialize);
    </script>
  </head>



</head>

<body>

<div class="container">

  <div class="header">
  </div>
  	<div class="menu_div">
    		<table class="menu_table"><tr class="menu"><td><a href="index.html">Domov</a></td><td><a href="friends.html">Priatelia</a></td><td><a href="places.html">Moje miesta</a></td><td><a href="null">Nastavenie</a></td></tr></table>
   	</div>
  <div class="content">
  
  	<div class="post">
    <div class="post_photo fltlft"><img class="post_photo" src="http://upload.wikimedia.org/wikipedia/commons/thumb/0/0c/Mark_Dayton_official_photo.jpg/819px-Mark_Dayton_official_photo.jpg">
    </div>
    <div class="post_comment fltlft">
    <p>Košice sú veľmi krásne mesto.</p>
    </div>
    <div id="map-canvas-01" class="post_map fltrt">
    </div>
    <div class="clearfloat"></div>
    </div>
    
    <div class="post">
    <div class="post_photo fltlft"><img class="post_photo" src="http://domaingang.com/wp-content/uploads/2010/11/enom-girl.jpg">
    </div>
    <div class="post_comment fltlft">
    <p>Tu som vyrastala. :)</p>
    </div>
    <div id="map-canvas-02" class="post_map fltrt">
    </div>
    <div class="clearfloat"></div>
    </div>
    
  	
    <!-- end .content --></div>
    <div class="footer"></div>
  <!-- end .container --></div>
</body>
</html>

WebApplication/mysite/PointsOfInterest/templates/PointsofInterest/login.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>

<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<title>Prihlásenie</title>
<link href="/static/style.css" rel="stylesheet" type="text/css">
</head>

<body>

<div class="container">

  <div class="header"></div>
  
	<div class="menu_div">
		<table class="menu_table">
			<tr class="menu makeborder">
				<td><a href="{% url 'PointsOfInterest:index' %}">Domov</a></td>
				<td><a href="{% url 'PointsOfInterest:friends' %}">Priatelia</a></td>
				<td><a href="{% url 'PointsOfInterest:places' %}">Moje miesta</a></td>
				{% if logged = False %}
				<td><a href="{% url 'PointsOfInterest:login' %}">Login</a></td>
				{% else %}
				<td><a href="{% url 'PointsOfInterest:logout' %}">Logout</a></td>
				{% endif %}
			</tr>
		</table>
	</div>
			
	<div class="content makeborder makeshadow">
		<div>
			{% if logged = False %}
			<div>{{message}}</div>
			<form action="{% url 'PointsOfInterest:login' %}" method="post">
				{% csrf_token %}
				Login: <input type="text" name="username"><br>
				Heslo: <input type="password" name="password"><br>
				<input type="submit" value="Submit">
			</form>
			{% else %}
			Gratulujeme, ste prihlaseny
			{% endif %}
		</div>
	</div>

	<div class="footer"></div>
</div>

</body>
</html>

WebApplication/mysite/PointsOfInterest/templates/PointsofInterest/place.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<title>{{ SITE_URL }} Bod {{place.title}}</title>
<link href="/static/style.css" rel="stylesheet" type="text/css">


<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCC5vyrqbcCQRVny8dQP5KhGq3W96kkfcU&sensor=false"></script>
	<script type="text/javascript">

		function initialize()
		{
        var mapOptions = {
          center: new google.maps.LatLng({{place.latitude}}, {{place.longitude}}),
          zoom: 8,
          mapTypeId: google.maps.MapTypeId.ROADMAP
        };
        var map = new google.maps.Map(document.getElementById("map-canvas-01"), mapOptions);
		
		var MarkerOptions = {
			position: new google.maps.LatLng({{place.latitude}}, {{place.longitude}}),
			map: map,
			title: "{{place.title}}"
		};
		var marker = new google.maps.Marker(MarkerOptions);
		}

      google.maps.event.addDomListener(window, 'load', initialize);
    </script>
  </head>



</head>

<body>

<div class="container">

  <div class="header">
  </div>
  	<div class="menu_div">
    		<table class="menu_table"><tr class="menu"><td><a href="index.html">Domov</a></td><td><a href="friends.html">Priatelia</a></td><td><a href="/POI/1/places">Moje miesta</a></td><td><a href="null">Nastavenie</a></td></tr></table>
   	</div>
  <div class="content">
  
  	<div class="place_container">
	<div class="place_title">{{place.title}}</div>
  	<div id="map-canvas-01" class="place_map"></div>
    <div class="place_desc"><p>Niečo o tomto bode: {{place.description}}</p></div>
    </div>

	<div class="place_gallery">
	<h4>Galéria</h4>
	</div>
    
    <div class="clearfloat"></div>
    
  	
    <!-- end .content --></div>
    <div class="footer"></div>
  <!-- end .container --></div>
</body>
</html>

WebApplication/mysite/PointsOfInterest/templates/PointsofInterest/places.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<title>Moje body</title>
<link href="/static/style.css" rel="stylesheet" type="text/css">


<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCC5vyrqbcCQRVny8dQP5KhGq3W96kkfcU&sensor=false"></script>
	<script type="text/javascript">
		function initialize()
		{
		{% for place in places %}
        var mapOptions{{forloop.counter}} = {
			center: new google.maps.LatLng({{place.latitude}}, {{place.longitude}}),
			zoom: 12,
			mapTypeId: google.maps.MapTypeId.ROADMAP,
			scrollwheel: false,
			navigationControl: false,
			mapTypeControl: false,
			scaleControl: false,
			draggable: false
        };
        var map{{forloop.counter}} = new google.maps.Map(document.getElementById("map-canvas-{{forloop.counter}}"), mapOptions{{forloop.counter}});
		
		var MarkerOptions{{forloop.counter}} = {
			position: new google.maps.LatLng({{place.latitude}}, {{place.longitude}}),
			map: map{{forloop.counter}},
			title: "{{place.title}} [{{place.latitude}}°, {{place.longitude}}°]"
		};
		var marker{{forloop.counter}} = new google.maps.Marker(MarkerOptions{{forloop.counter}});
		{% endfor %}
		}
      google.maps.event.addDomListener(window, 'load', initialize);
    </script>
  </head>



</head>

<body>

<div class="container">

  <div class="header">
  </div>
  	<div class="menu_div">
    	<table class="menu_table">
				<tr class="menu makeborder">
					<td><a href="{% url 'PointsOfInterest:index' %}">Domov</a></td>
					<td><a href="{% url 'PointsOfInterest:friends' %}">Priatelia</a></td>
					<td><a href="{% url 'PointsOfInterest:places' %}">Moje miesta</a></td>
					{% if request.session.logged > 0 %}
					<td><a href="{% url 'PointsOfInterest:login' %}">Login out</a></td>
					{% else %}
					<td><a href="{% url 'PointsOfInterest:logout' %}">Logout</a></td>
					{% endif %}
				</tr>
			</table>
   	</div>
  <div class="content">
  
	{% for place in places %}
  	<div class="places_place">
	<div class="place_title"><a href="{% url 'PointsOfInterest:place' place.id %}">{{place.title}}</a></div>
  	<div id="map-canvas-{{forloop.counter}}" class="place_map"></div>
    </div>
	{% endfor %}
    
  	
    <!-- end .content --></div>
    <div class="footer"></div>
  <!-- end .container --></div>
</body>
</html>

WebApplication/mysite/PointsOfInterest/templates/sablona/friends.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<title>Dokument bez názvu</title>
<link href="style.css" rel="stylesheet" type="text/css">

<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCC5vyrqbcCQRVny8dQP5KhGq3W96kkfcU&sensor=false"></script>
	<script type="text/javascript">
		function initialize()
		{
        var mapOptions = {
          center: new google.maps.LatLng(48.717, 21.25),
          zoom: 8,
          mapTypeId: google.maps.MapTypeId.ROADMAP
        };
        var map = new google.maps.Map(document.getElementById("map-canvas-01"), mapOptions);
		
		var MarkerOptions = {
			position: new google.maps.LatLng(48.717, 21.25),
			map: map,
			title: 'Moje oblubene miesto'
		};
		var marker = new google.maps.Marker(MarkerOptions);
		
		
		
		var mapOptions = {
		  center: new google.maps.LatLng(31.717, 31.25),
          zoom: 8,
          mapTypeId: google.maps.MapTypeId.ROADMAP
        };
		
		var map = new google.maps.Map(document.getElementById("map-canvas-02"), mapOptions);
		
		var MarkerOptions = {
			position: new google.maps.LatLng(31.717, 31.25),
			map: map,
			title: 'Tu som bol pri mori'
		};
		var marker = new google.maps.Marker(MarkerOptions);
			
		
		}
      google.maps.event.addDomListener(window, 'load', initialize);
    </script>
  </head>



</head>

<body>

<div class="container">

  <div class="header">
  </div>
  	<div class="menu_div">
    		<table class="menu_table"><tr class="menu"><td><a href="index.html">Domov</a></td><td><a href="friends.html">Priatelia</a></td><td><a href="places.html">Moje miesta</a></td><td><a href="null">Nastavenie</a></td></tr></table>
   	</div>
  <div class="content">
  
  	<div class="friend">
    <img class="friend_photo" src="http://upload.wikimedia.org/wikipedia/commons/thumb/0/0c/Mark_Dayton_official_photo.jpg/819px-Mark_Dayton_official_photo.jpg">
    <div align="center">Jozef123</div>
    </div>
    
    
    <div class="friend">
    <img class="friend_photo" src="http://domaingang.com/wp-content/uploads/2010/11/enom-girl.jpg">
    <div align="center">Janka555</div>
    </div>
    <div class="clearfloat"></div>  
    
    
  	
    <!-- end .content --></div>
    <div class="footer"></div>
  <!-- end .container --></div>
</body>
</html>